http:
  host: 0.0.0.0
  port: 8085
  llm: Qwen3-Coder-REAP-25B-A3B-MXFP4_MOE-GGUF:latest
  prompt_ru: Пользователь хочет знать о "${question}". Дай короткое обобщение по тому что хочет знать пользователь, используя данные предоставлненные пользователем
  prompt_en: User wants to know about '${question}'. Shorten this user query to its core meaning. Then use the extracted passages from our knowledge base (below) to form the best answer you can. Show the final answer clearly.User wants to know about "${question}". Use the extracted passages from our knowledge base (below) to form the best answer you can. 
ollama:
  embedding:
    chunk_overlap_percent: 30
    context_size: 4096
    keep_alive: 24h
    model: qwen3-embedding:latest 
    token_naive_k: 2.2
  url: http://192.168.0.101:11434
path:
  input: input
  output: db-data
process:
  pdf_clip:
  - footer_height: 50
    header_height: 50
    text: Протокол и основные функциональные
  - footer_height: 50
    header_height: 0
    text: JAX-RS
  silent: false
qdrant:
  collection_name: my_documents
  distance: Dot
  top_results: 10
  url: http://192.168.0.101:6333
  vector_sz: 4096
confluence:
  date_threshold: 2010-01-01T12:00:00
